<link href="${r_c}/css/reset.css" rel="stylesheet" type="text/css" />
<link href="${r_t}/css/whole.css" type="text/css" rel="stylesheet" />
<link href="${r_t}/css/layout.css" type="text/css" rel="stylesheet" />
<link href="${r_t}/css/front.css" type="text/css" rel="stylesheet" />

<script src="${r_c}/jquery/jquery.js" type="text/javascript"></script>
<script src="${r_c}/js/pony.js" type="text/javascript"></script>
<script src="${r_c}/js/front.js" type="text/javascript"></script>