<%@page contentType="text/html; charset=UTF-8"%>

<base href="<%=baseMngPath%>">

<link href="<%=r_c%>/css/reset.css" rel="stylesheet" type="text/css" />
<link href="<%=r_c%>/css/fonts.css" rel="stylesheet" type="text/css" />
<link href="<%=r_m%>/css/comm.css" rel="stylesheet" type="text/css" />
<link href="<%=r_m%>/css/main.css" rel="stylesheet" type="text/css" />

<!-- Jquery -->
<script type="text/javascript" src="<%=r_c%>/jquery/jquery.js"></script>
<script type="text/javascript" src="<%=r_c%>/jquery/jquery.cookie.js"></script>
<script type="text/javascript" src="<%=r_c%>/jquery/jquery.imgareaselect.js"></script>
<script type="text/javascript" src="<%=r_c%>/jquery/jquery.validate.js"></script>
<script type="text/javascript" src="<%=r_c%>/jquery/jquery.ext.js"></script>

<!-- ALL jQuery Tools. No jQuery library -->
<script type="text/javascript" src="<%=r_c%>/jquery/jquery-tools/jquery.tools.min.js"></script>
<link href="<%=r_c%>/jquery/jquery-tools/jquery.tools.css" rel="stylesheet" type="text/css" />

<!-- Jquery UI -->
<script type="text/javascript" src="<%=r_c%>/jquery/jquery-ui/jquery.ui.min.js"></script>
<link href="<%=r_c%>/jquery/jquery-ui/jquery.ui.css" rel="stylesheet" type="text/css" />

<!-- Jquery Treeview -->
<script type="text/javascript" src="<%=r_c%>/jquery/jquery-treeview/jquery.treeview.js"></script>
<script type="text/javascript" src="<%=r_c%>/jquery/jquery-treeview/jquery.treeview.async.js"></script>
<link href="<%=r_c%>/jquery/jquery-treeview/jquery.treeview.css" rel="stylesheet" type="text/css" />

<script type="text/javascript" src="<%=r_c%>/datePicker/WdatePicker.js"></script>
<script type="text/javascript" src="<%=r_c%>/js/pony.js"></script>
<script type="text/javascript" src="<%=r_c%>/js/checkcode.js"></script>
<script type="text/javascript" src="<%=r_c%>/js/manage.js"></script>

<!-- prompt -->
<link href="<%=r_c%>/ymPrompt/skin/default/ymPrompt.css" rel="stylesheet" type="text/css" />
<script src="<%=r_c%>/ymPrompt/skin/default/ymPrompt.js" type="text/javascript" ></script>
<script src="<%=r_c%>/ymPrompt/ymPrompt_Ex.js" type="text/javascript" ></script>

<!--
<script type="text/javascript" src="<%=r_c%>/js/msg.js"></script>
<script type="text/javascript" src="<%=r_c%>/js/jspMsg.jsp"></script>
-->
