<script src="${resSys}/jquery/jquery.js" type="text/javascript"></script>
<script src="${resSys}/festival/festival.js" type="text/javascript"></script>
<script src="${resTpl}/js/front.js" type="text/javascript"></script>
<!--<script type="text/javascript">$(function() {Cms.siteFlow("${base}", location.href, document.referrer);});</script>-->
<link href="${resTpl}/css/front.css" rel="stylesheet" type="text/css" />